// <auto-generated />
using System;
using DoctorRx.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorRx.Infrastructure.Migrations
{
    [DbContext(typeof(DoctorRxDbContext))]
    [Migration("20261008184938_AddSearchTokensAndIndexes")]
    partial class AddSearchTokensAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DoctorRx.Domain.Entities.AppMeta", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppMetas", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClinicAddress")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicPhone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FooterText")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderText")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Draft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DraftKey")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DraftKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Drafts_DraftKey");

                    b.HasIndex("PatientId");

                    b.ToTable("Drafts", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenericName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("GenericName")
                        .HasDatabaseName("IX_Medicines_GenericName");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Medicines_Name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Medicines_NormalizedName");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("IX_Medicines_UsageCount");

                    b.ToTable("Medicines", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.MedicineSearchToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TokenType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("Token", "MedicineId")
                        .HasDatabaseName("IX_MedicineSearchTokens_Token_MedicineId");

                    b.ToTable("MedicineSearchTokens", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.NumberSequence", b =>
                {
                    b.Property<string>("SequenceKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("SequenceKey");

                    b.ToTable("NumberSequences", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AgeRecordedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("KnownAllergies")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastVisitDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistoryNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneDigits")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived")
                        .HasDatabaseName("IX_Patients_IsArchived");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Patients_Name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Patients_NormalizedName");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Patients_Phone");

                    b.HasIndex("PhoneDigits")
                        .HasDatabaseName("IX_Patients_PhoneDigits");

                    b.HasIndex("RecordNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_RecordNumber");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.PatientSearchToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TokenType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("Token", "PatientId")
                        .HasDatabaseName("IX_PatientSearchTokens_Token_PatientId");

                    b.ToTable("PatientSearchTokens", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmendmentNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChiefComplaints")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClinicalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FinalizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FollowUpDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowUpText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralAdvice")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentPrescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PrescriptionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriptionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PulseRate")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Temperature")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeightKg")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ParentPrescriptionId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionDate")
                        .HasDatabaseName("IX_Prescriptions_Date");

                    b.HasIndex("PrescriptionNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Prescriptions_Number");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.PrescriptionMedicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomMealRelationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenericName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MealRelation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedicineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timing")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WithWhat")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionMedicines", (string)null);
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Draft", b =>
                {
                    b.HasOne("DoctorRx.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.MedicineSearchToken", b =>
                {
                    b.HasOne("DoctorRx.Domain.Entities.Medicine", "Medicine")
                        .WithMany("SearchTokens")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.PatientSearchToken", b =>
                {
                    b.HasOne("DoctorRx.Domain.Entities.Patient", "Patient")
                        .WithMany("SearchTokens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("DoctorRx.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoctorRx.Domain.Entities.Prescription", "ParentPrescription")
                        .WithMany()
                        .HasForeignKey("ParentPrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DoctorRx.Domain.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DoctorRx.Domain.ValueObjects.DoctorSnapshot", "DoctorSnapshot", b1 =>
                        {
                            b1.Property<int>("PrescriptionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClinicAddress")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_ClinicAddress");

                            b1.Property<string>("ClinicName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_ClinicName");

                            b1.Property<string>("ClinicPhone")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_ClinicPhone");

                            b1.Property<string>("FooterText")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_FooterText");

                            b1.Property<string>("HeaderText")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_HeaderText");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_Name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_Phone");

                            b1.Property<string>("Qualification")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_Qualification");

                            b1.Property<string>("RegistrationNumber")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_RegistrationNumber");

                            b1.Property<string>("Specialization")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Doctor_Specialization");

                            b1.HasKey("PrescriptionId");

                            b1.ToTable("Prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionId");
                        });

                    b.OwnsOne("DoctorRx.Domain.ValueObjects.PatientSnapshot", "PatientSnapshot", b1 =>
                        {
                            b1.Property<int>("PrescriptionId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AgeText")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Patient_AgeText");

                            b1.Property<int>("Gender")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Patient_Gender");

                            b1.Property<string>("KnownAllergies")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Patient_KnownAllergies");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("TEXT")
                                .HasColumnName("Patient_Name");

                            b1.Property<string>("Phone")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("Patient_Phone");

                            b1.HasKey("PrescriptionId");

                            b1.ToTable("Prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionId");
                        });

                    b.Navigation("Doctor");

                    b.Navigation("DoctorSnapshot")
                        .IsRequired();

                    b.Navigation("ParentPrescription");

                    b.Navigation("Patient");

                    b.Navigation("PatientSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.PrescriptionMedicine", b =>
                {
                    b.HasOne("DoctorRx.Domain.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DoctorRx.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Medicine", b =>
                {
                    b.Navigation("SearchTokens");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Prescriptions");

                    b.Navigation("SearchTokens");
                });

            modelBuilder.Entity("DoctorRx.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
